name: WML
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Clone the Wesnoth Github repository without checking it out.
      run: |
        git clone --filter=blob:none --no-checkout --depth 1 --sparse --branch 1.18 https://github.com/wesnoth/wesnoth.git

    - name: Set sparse checkout to only fetch the data/ directory
      working-directory: ./wesnoth
      run: |
        git sparse-checkout set data

    - name: Checkout branch 1.18
      working-directory: ./wesnoth
      run: |
        git checkout

    - name: Run wmllint and filter out findings from core
      run: |
        wesnoth/data/tools/wmllint -S -d wesnoth/data/core . > >(grep -v "wesnoth") 2> >(grep -v "wesnoth" >&2)

    - name: Run wmlindent
      run: |
        wesnoth/data/tools/wmlindent -d .

    - name: Run wmlscope and filter out findings from core
      run: |
        wesnoth/data/tools/wmlscope -d wesnoth/data/core . > >(grep -v "wesnoth") 2> >(grep -v "wesnoth" >&2)
