name: WML
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Clone the Wesnoth Github repository without checking it out.
      run: |
        git clone --filter=blob:none --no-checkout --depth 1 --sparse --branch 1.18 https://github.com/wesnoth/wesnoth.git

    - name: Change into the wesnoth directory
      run: |
        cd wesnoth

    - name: Set sparse checkout to only fetch the data/ directory
      run: |
        git sparse-checkout set data

    - name: Checkout branch 1.18
      run: |
        git checkout

    - name: Change back into the working directory
      run: |
      cd ..

    - name: Run wmllint
      run: |
        wesnoth/data/tools/wmllint -S -d wesnoth/data/core . | grep -v wesnoth/

    - name: Run wmlindent
      run: |
        wesnoth/data/tools/wmlindent -d .

    - name: Run wmlscope
      run: |
        wesnoth/data/tools/wmlscope -d wesnoth/data/core . | grep -v wesnoth/
